name: Build SteamOS Edge ISO Upstream

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install host dependencies for Arch bootstrap and chroot
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync zstd


      - name: Setup Arch Linux chroot environment
        run: |
          set -e
          sudo mkdir -p /mnt/arch

          ARCH_BASE_URL="https://mirror.rackspace.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.zst"
          sudo curl -L -o /tmp/archlinux-bootstrap.tar.zst "$ARCH_BASE_URL"
          sudo zstd -d /tmp/archlinux-bootstrap.tar.zst -c | sudo tar -x -C /mnt/arch --strip-components=1


          echo "Extracting Arch Linux bootstrap..."
          sudo tar -xzf /tmp/archlinux-bootstrap.tar.gz -C /mnt/arch --strip-components=1

          echo "Mounting /dev, /proc, /sys into chroot..."
          sudo mount --bind /dev /mnt/arch/dev
          sudo mount --bind /proc /mnt/arch/proc
          sudo mount --bind /sys /mnt/arch/sys

          echo "Initializing pacman keys and updating system inside chroot..."
          sudo chroot /mnt/arch /bin/bash -c "
            pacman-key --init
            pacman-key --populate archlinux
            pacman -Sy --noconfirm
          "

          echo "Installing mkedge build dependencies inside chroot..."
          sudo chroot /mnt/arch /bin/bash -c "
            pacman -S --noconfirm arch-install-scripts base-devel git squashfs-tools mtools dosfstools \
            xorriso e2fsprogs erofs-utils libarchive libisoburn gnupg grub \
            openssl python-docutils shellcheck
          "

      - name: Copy source code to chroot
        run: |
          sudo rsync -a --exclude=out ./ /mnt/arch/root/steamos-edge/

      - name: Run mkedge build inside chroot
        run: |
          sudo chroot /mnt/arch /bin/bash -c "
            cd /root/steamos-edge
            chmod +x ./mkedgescript
            ./mkedgescript --mode 2 --extra --neptune --cowspace skip --build --bypass
          "

      - name: Copy ISO output back to workspace
        run: |
          sudo rsync -a /mnt/arch/root/steamos-edge/out ./out

      - name: Cleanup chroot mounts
        if: always()
        run: |
          sudo umount /mnt/arch/dev || true
          sudo umount /mnt/arch/proc || true
          sudo umount /mnt/arch/sys || true
          sudo rm -rf /mnt/arch

      - name: Split ISO into 1.9GB chunks
        run: |
          cd out
          ISO_FILE=$(ls *.iso | head -n 1)
          echo "Found ISO: $ISO_FILE"
          split -b 1900M "$ISO_FILE" "${ISO_FILE}.part"
          ls -lh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ github.sha }}"
          name: "SteamOS Edge Build ${{ github.sha }}"
          files: |
            out/*.iso.part*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
