name: Build SteamOS Edge ISO 32

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies for mkedge
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            arch-install-scripts base-devel git squashfs-tools mtools dosfstools \
            xorriso e2fsprogs erofs-utils libarchive libisoburn gnupg \
            grub openssl python-docutils shellcheck

      - name: Build ISO with mkedge
        run: |
          chmod +x ./mkedgescript
          ./mkedgescript --mode 3 --cowspace skip --build --bypass

      - name: Split ISO into 1.9GB chunks
        run: |
          cd out
          ISO_FILE=$(ls *.iso | head -n 1)
          echo "Found ISO: $ISO_FILE"
          split -b 1900M "$ISO_FILE" "${ISO_FILE}."
          ls -lh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ github.sha }}"
          name: "SteamOS Edge Build ${{ github.sha }}"
          files: |
            out/*.iso.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

